# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Gony's blog
subtitle: ''
description: ''
keywords:
author: Gony
language: zh-Hans
timezone: ''
banner:
  default:
    type: img
    bgurl: /images/banner/1.webp
    bannerText: GM!
    position: top
    fit: cover
  index:
    type: img
    bgurl: /images/banner/1.webp
    bannerTitle: Freedom;<br>Building;<br>Stronger;<br>
    bannerText: GM!
  archives:
    bannerTitle: Freedom;<br>Building;<br>Stronger;<br>
    bannerText: GM!
  links:
      bannerTitle: Freedom;<br>Building;<br>Stronger;<br>
      bannerText: A link to a friend's website
  comment:
      bannerTitle: Freedom;<br>Building;<br>Stronger;<br>
      bannerText: GM!
  about:
      bannerTitle: Freedom;<br>Building;<br>Stronger;<br>
      bannerText: About me
favicon:
  logo: /images/favicon/favicon.ico
  icon16: /images/favicon/favicon-16x16.png
  icon32: /images/favicon/favicon-32x32.png
  appleTouchIcon: /images/favicon/apple-touch-icon.png
  visibilitychange: false
toc:
  enable: true
  list_number: true
  post_title: false
  max_depth: 2
  min_depth: 1
user:
  name: Gony
  first_name: Jean
  last_name: Gony
  email: gony952701@gmail.com
  domain: https://www.xx.com
  avatar: /images/avatar.gif
  describe: 网站简介。
  ruleText: 
top_bars:
  - title: menu.home
    url: /
  - title: menu.archives
    url: /archives/
  - title: 分类
    url: /categories/
footer:
  powered:
    enable: false
sidebar:
  social: # 社交地址
    - name: github
      icon: fab fa-github
      url: https://github.com/GonyJean
categorie_card:
  enable: false
  len: 3
  list: 
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme:
  switch: true
  default: style-dark

# Customize the template path
layout:
  path: layout
  # layout
  # post
  post_card_mini: _partial/post/post-card-mini
  
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
